[package]
name = "jscjs_sys"
version = "0.0.1"
authors = ["bynx <drtychai@protonmail.com>"]
description = "System crate for the Webkit JavaScriptCore JavaScript engine."
repository = "https://github.com/drtychai/jsc-sys"
license = "MPL-2.0"
edition = "2018"
build = "build.rs"

[lib]
name = "jscjs_sys"
path = "src/lib.rs"

[dependencies]
libc = "0.2.76"
libz-sys = "1.1.1"

[build-dependencies]
bindgen = "0.55.1"
pkg-config = "0.3.14"
cmake = "0.1.44"
clang = "1.0.1"
walkdir = "2.3.1"
