[package]
name = "jsc_sys"
version = "0.0.1"
authors = ["bynx <drtychai@protonmail.com>"]
build = "build.rs"
edition = "2018"
description = "Raw bindings to JavaScriptCore APIs"
repository = "https://github.com/drtychai/jsc-sys"
license = "MIT"
include = [
    "WebKit/Source/JavaScriptCore",
    "WebKit/WebKitBuild/Debug/DerivedSources/ForwardingHeaders/JavaScriptCore"
]

[lib]
name = "jsc_sys"
path = "src/lib.rs"

[dependencies]
encoding_c = "0.9.6"
encoding_c_mem = "0.2.5"
libc = "0.2"
libz-sys = "1.0"

[build-dependencies]
bindgen = "*"
pkg-config = "0.3.14"
cmake = "*"
clang = "*"
walkdir = "*"
