[package]
build = "build.rs"
name = "jscjs_sys"
version = "0.1.0"

[lib]
name = "jscjs_sys"
path = "src/lib.rs"

[[bin]]
name = "runner"
path = "src/main.rs"

[dependencies]
url = "*"

[build-dependencies]
bindgen = "*"
